# difference of elements of array

A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.


In [22]:
import numpy as np
arr = np.array([4,3,7,8,5,1,0,6,9])
newarr = np.diff(arr) #  it even accepts frequency of this operation
newarr2 = np.diff(arr, n=3) 

print(newarr)
print(newarr2)

[-1  4  1 -3 -4 -1  6  3]
[ -8  -1   3   4   4 -10]


In [16]:
arr = np.arange(1,6)
arr2 = np. arange(4,9)
newarr = np.prod([arr,arr2]) # multiplies all elements of both arrays
print(newarr)

806400


# product via axis

In [17]:
arr = np.arange(1,6)
arr2 = np. arange(4,9)
newarr = np.prod([arr,arr2], axis= 1)
print(newarr)

[ 120 6720]


cummulative product

In [19]:
arr= np.array([3,1*2,4*1])
print(arr) # this is not cummulative product
newarr = np.cumprod(arr) # the elements goes on multiplying to preceeding one
print(newarr)

[3 2 4]
[ 3  6 24]
