# addition vs summation 

In [7]:
import numpy as np
arr = np.arange(1,6)
arr2 = np. arange(4,9)
newarr = np.add(arr,arr2)
print(newarr)

[ 5  7  9 11 13]


In [9]:
arr = np.arange(1,6)
arr2 = np. arange(4,9)
newarr = np.sum([arr,arr2])
print(newarr)

45


# summation via axis

In [10]:
arr = np.arange(1,6)
arr2 = np. arange(4,9)
newarr = np.sum([arr,arr2], axis= 1)
print(newarr)

[15 30]


cummulative sum

In [12]:
arr= np.array([3,2+1,5-2])
print(arr) # this is not cummulative sum
newarr = np.cumsum(arr) # the elements goes on summu
print(newarr)

[3 3 3]
[3 6 9]
